server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment-route
          uri: lb://cloud-payment-hystrix-service
          predicates:
            - Path=/provider/**
        - id: order-route
          uri: lb://cloud-order-hystrix-service
          predicates:
            - Path=/order/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

